// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhpGxONhP6R1mv-4Gr7yv5_5Y8LaAtFo8',
    appId: '1:613623978514:web:01789d397bd71e9d8616cb',
    messagingSenderId: '613623978514',
    projectId: 'remote-config-study',
    authDomain: 'remote-config-study.firebaseapp.com',
    storageBucket: 'remote-config-study.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIAVNyBxnUNG9ikdvPnAx47yonl_OdyaA',
    appId: '1:613623978514:android:08d4f5dc631370ef8616cb',
    messagingSenderId: '613623978514',
    projectId: 'remote-config-study',
    storageBucket: 'remote-config-study.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNP1Put46b8Ja5aSC8FnOZVyhIFRhveZE',
    appId: '1:613623978514:ios:3b2ddb7a1efbadd18616cb',
    messagingSenderId: '613623978514',
    projectId: 'remote-config-study',
    storageBucket: 'remote-config-study.appspot.com',
    iosClientId: '613623978514-vuhuhinfsvrfalnkmhf9gl94th9tkb98.apps.googleusercontent.com',
    iosBundleId: 'com.example.remoteConfigStudy',
  );
}
